### ISSUE TITLE
no value for $CURRENT_USER

### ISSUE THREAD

**Issue by musfandi** [rezo-labs/directus-extension-computed-interface#29]
no value for {{ STRING($CURRENT_USER.staff_no) }} and also {{ YEAR($NOW) }} in field .. 
using  "directus-extension-computed-interface": "^1.4.0",

**Comment by duydvu** [comment]
Yeah `{{ YEAR($NOW) }}` doesn't work because it will only compute when the template uses at least one field. To fix this, I guess it will need to compute initially on mount.

I didn't read the doc carefully so I thought `$CURRENT_USER` just returns the user's id 😅. Don't worry, should be fast to fix.
