### ISSUE TITLE
Others functions [SUGGESTION - FEATURE REQUESTS]

### ISSUE THREAD

**Issue by corentiny1** [rezo-labs/directus-extension-computed-interface#4]
Hi there, great job !
It will be great if we can use others functions like :
- IF / ELSE
- NULL / NOTNULL
- LEFT / RIGHT
- Examples : https://support.airtable.com/docs/formula-field-reference

**Comment by duydvu** [comment]
Thanks for your feedback @corentiny1 !

LEFT / RIGHT seems fairly easy so we can make it fast.
IF / ELSE may need a way to parse boolean expressions. Instead of regular < > =, it will be easier to transform to functions like EQUAL, GT, LT, etc.
I'm not quite sure about what NULL / NOTNULL will do. Does it check for null values?
