### ISSUE TITLE
Interface should compute if NULL

### ISSUE THREAD

**Issue by emahuni** [rezo-labs/directus-extension-computed-interface#43]
I had countless trials and errors before I figured this out, I am sure a lot of people go through the same. I actually thought something was wrong with the extension itself.

- To reproduce this, create a collection with fields `a` and `b` and save an item for it.
- Now modify the collection and add a computed field `c` that adds `a` and `b`. 
- Go back to the collection item and notice the field doesn't show anything.

I thought that something was wrong with my syntax and tried changing to different templates etc, it only worked when I use relation fields (because it had to do something before it displays), which is how I figured out that the interface is calculating this lazily. I now understand that it only calculates when a and b are changed. But a and b already had values. Since this is a new compute field it should initialize by doing what is expected of it.

What I think this should do is, it should initially calculate if its own value is NULL, meaning that it has never done anything before. If it's not NULL then there is a cached value there and it should then lazily wait for changes.

**Comment by duydvu** [comment]
Sorry for replying late.
If I remember correctly, I tried making the interface compute initially and it caused some confusion for the users since they haven't made any changes but the Save button is still enabled. So I turned it off.

Now that I have revisited it, sacrificing functionality for UX is not a good approach. But before the change comes out, I need to test it thoroughly. So please wait a bit more.

**Comment by duydvu** [comment]
Hi @emahuni , I just added a new option called "Compute If Empty". You might need to enable this option before testing.
If there are any bugs, please let me know. Thanks
