### ISSUE TITLE
Compute on the collection table level

### ISSUE THREAD

**Issue by falmanna** [rezo-labs/directus-extension-computed-interface#58]
Hey,

Is it possible to force computing the value on the collection level? 
I know it might be an expensive operation, but say I am willing to delay displaying the data until this is computed.

**Comment by duydvu** [comment]
Hello @falmanna ,

I'm afraid that it is out of scope for this extension because this is an Interface extension, which means that it can only be used inside a form. What you are describing is a Display extension, you would need a new extension to do that.

I also tried implementing it before but Directus does not provide enough flexibility to calculate based on other fields.

**Comment by falmanna** [comment]
Hey @duydvu ,

I see, thanks for the quick prompt and for this amazing extension. Figures crossed hoping that directus will implement `$CURRENT_ITEM` sometime soon.

Please feel free to close this if you want.
